### ISSUE TITLE
suggested README improvements

### ISSUE THREAD

**Issue by o-smirnov** [tart-telescope/tart_cargo#1]
Thanks @tmolteno! May I suggest some improvements to the recipe in the README, in the interest of promoting best practices:

```yml
    assign:
        api: = 'https://api.elec.ac.nz/tart/{recipe.tart}'
        hdf: = 'vis_{recipe.tart}.hdf'
        ms: = '{recipe.tart}.ms'
```

The ``=`` is unnecessary since only {}-substitution is being done. Also, suggest rather defining ``hdf`` and ``ms`` as explicit outputs of the recipe (with defaults as above), so that the user can easily rename them as needed. Something like:

```yml
outputs:
  ms:
    dtype: MS
    default:  '{current.tart}.ms'
  hdf:
    dtype: File
    default: =STRIPEXT(current.ms) + '-vis.hdf'
```

Then:

```yml
        create-ms:
            cab: tart2ms
            params:
                hdf: =recipe.hdf
```

Better ``hdf: =steps.download-hdf.hdf``, to make the linkage between steps explicit.

```yml
        disko-image:
            cab: disko
            params:
                ms: =recipe.ms
                HDF: '{recipe.tart}.h5'
```

Likewise, ``ms: =steps.create-ms.ms``, and perhaps ``HDF: =STRIPEXT(current.ms) + '.h5'``, to ensure name is consistent with MS.

```yml
        project-image:
            cab: disko-draw
            params:
                hdf: '{recipe.tart}.h5'
                SVG: '{recipe.tart}.svg'
```

Likewise, ``hdf: =steps.disko-image.HDF`` and ``SVG: =STRIPEXT(current.hdf) + '.svg'``.

Can even make the ``SVG`` an explicit output of the recipe, as:

```yml
outputs:
    svg:
      default: =STRIPEXT(current.ms) + '.svg'``
      aliases: [project-image.SVG]
```

....and in this case you do not need to define it at ``project-image`` level.
